### ISSUE TITLE
Add scripts to TOML file

### ISSUE THREAD

**Issue by mjennings061** [mjennings061/viking-log-keeper#14]
As a user, I want to call the log keeper from command line, so that I do not need to type a lengthy "python -m ..." script

Dev notes:
- Add a `[python.scripts]` part to the `pyproject.toml` file e.g.

```toml
[project.scripts]
update-log-keeper = "log_keeper.main"
```
